@extends('layouts.app')

@section('title', 'Procurement Requests')

@section('content')
<div class="space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 animate-fade-in-up">
        <div>
            <h1 class="text-3xl font-bold text-gray-900 font-poppins">Procurement Requests</h1>
            <p class="text-gray-600">Manage procurement and replenishment workflows</p>
        </div>
        <div class="flex space-x-3">
            <a href="{{ route('procurement.dashboard') }}" class="inline-flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-700 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path></svg>
                Dashboard
            </a>
            <a href="{{ route('procurement.create') }}" class="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-2.5 rounded-xl text-sm font-semibold shadow-sm hover:shadow-md transition-all duration-200">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                New Request
            </a>
        </div>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 animate-fade-in-up stagger-1">
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-yellow-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Pending</p>
            <p class="text-3xl font-bold text-yellow-600 mt-1 font-poppins">{{ $pendingCount }}</p>
        </div>
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-purple-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Auto-Generated</p>
            <p class="text-3xl font-bold text-purple-600 mt-1 font-poppins">{{ $autoGeneratedCount }}</p>
        </div>
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-green-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Total Requests</p>
            <p class="text-3xl font-bold text-green-600 mt-1 font-poppins">{{ $procurementRequests->total() }}</p>
        </div>
    </div>

    <!-- Generate Alerts -->
    <div class="flex justify-end animate-fade-in-up stagger-2">
        <form method="POST" action="{{ route('procurement.generate-low-stock-alerts') }}">
            @csrf
            <button type="submit" class="inline-flex items-center gap-2 bg-amber-500 hover:bg-amber-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold shadow-sm hover:shadow-md transition-all duration-200">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path></svg>
                Generate Low Stock Alerts
            </button>
        </form>
    </div>

    <!-- Requests Table -->
    <div class="bg-white rounded-2xl ring-1 ring-gray-200 shadow-sm overflow-hidden animate-fade-in-up stagger-3">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr class="border-b border-gray-100">
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Item</th>
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Supplier</th>
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Qty</th>
                        <!-- Total column removed by client request -->
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Urgency</th>
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Status</th>
                        <th class="text-left px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Requester</th>
                        <th class="text-right px-6 py-4 font-semibold text-gray-600 uppercase tracking-wide text-xs">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-50">
                    @forelse($procurementRequests as $request)
                    <tr class="hover:bg-gray-50/50 transition-colors">
                        <td class="px-6 py-4">
                            <div class="font-medium text-gray-900">{{ $request->item?->name ?? 'N/A' }}</div>
                            @if($request->auto_generated)
                                <span class="text-xs font-semibold text-purple-600">Auto-generated</span>
                            @endif
                        </td>
                        <td class="px-6 py-4 text-gray-700">{{ $request->supplier?->name ?? 'N/A' }}</td>
                        <td class="px-6 py-4 text-gray-900 font-semibold">{{ $request->quantity }}</td>
                        <td class="px-6 py-4">
                            @php
                                $urgencyColors = [
                                    'low' => 'bg-gray-100 text-gray-700',
                                    'medium' => 'bg-blue-50 text-blue-700',
                                    'high' => 'bg-orange-50 text-orange-700',
                                    'critical' => 'bg-red-50 text-red-700',
                                ];
                            @endphp
                            <span class="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-semibold {{ $urgencyColors[$request->urgency_level] ?? 'bg-gray-100 text-gray-700' }}">
                                {{ ucfirst($request->urgency_level) }}
                            </span>
                        </td>
                        <td class="px-6 py-4">
                            @php
                                $statusColors = [
                                    'pending' => 'bg-yellow-50 text-yellow-700',
                                    'approved' => 'bg-green-50 text-green-700',
                                    'ordered' => 'bg-blue-50 text-blue-700',
                                    'received' => 'bg-emerald-50 text-emerald-700',
                                    'rejected' => 'bg-red-50 text-red-700',
                                ];
                            @endphp
                            <span class="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-semibold {{ $statusColors[$request->status] ?? 'bg-gray-100 text-gray-700' }}">
                                {{ ucfirst($request->status) }}
                            </span>
                        </td>
                        <td class="px-6 py-4 text-gray-700">{{ $request->requester->name ?? 'System' }}</td>
                        <td class="px-6 py-4 text-right">
                            <div class="flex items-center justify-end space-x-2">
                                @if($request->status === 'pending')
                                <form method="POST" action="{{ route('procurement.approve', $request) }}" x-data @submit.prevent="$dispatch('open-confirm-modal', { form: $el, title: 'Approve Procurement', message: 'Are you sure you want to approve this procurement request?', type: 'success' })">
                                    @csrf @method('PATCH')
                                    <button type="submit" class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-green-50 text-green-700 hover:bg-green-100 ring-1 ring-green-200/60 transition-all duration-200">
                                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                                        Approve
                                    </button>
                                </form>
                                @endif
                                @if($request->status === 'approved')
                                <form method="POST" action="{{ route('procurement.mark-ordered', $request) }}">
                                    @csrf @method('PATCH')
                                    <button type="submit" class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-blue-50 text-blue-700 hover:bg-blue-100 ring-1 ring-blue-200/60 transition-all duration-200">
                                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
                                        Mark Ordered
                                    </button>
                                </form>
                                @endif
                                @if($request->status === 'ordered')
                                <form method="POST" action="{{ route('procurement.mark-received', $request) }}">
                                    @csrf @method('PATCH')
                                    <button type="submit" class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-emerald-50 text-emerald-700 hover:bg-emerald-100 ring-1 ring-emerald-200/60 transition-all duration-200">
                                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                                        Received
                                    </button>
                                </form>
                                @endif
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="px-6 py-12 text-center text-gray-400">
                            <svg class="w-12 h-12 mx-auto mb-3 opacity-40" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 100 4 2 2 0 000-4z"></path></svg>
                            <p>No procurement requests found</p>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <div class="px-6 py-4 border-t border-gray-100">
            {{ $procurementRequests->links() }}
        </div>
    </div>
</div>
@endsection
