

<?php $__env->startSection('title', 'Procurement Dashboard'); ?>

<?php $__env->startSection('content'); ?>
<div class="space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 animate-fade-in-up">
        <div>
            <h1 class="text-3xl font-bold text-gray-900 font-poppins">Procurement Dashboard</h1>
            <p class="text-gray-600">Supply chain analytics & automated replenishment alerts</p>
        </div>
        <div class="flex space-x-3">
            <a href="<?php echo e(route('procurement.index')); ?>" class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-5 py-2.5 rounded-xl font-semibold transition-all duration-200">View All Requests</a>
            <form method="POST" action="<?php echo e(route('procurement.generate-low-stock-alerts')); ?>">
                <?php echo csrf_field(); ?>
                <button type="submit" class="bg-green-600 hover:bg-green-700 text-white px-5 py-2.5 rounded-xl font-semibold transition-all duration-200 shadow-sm hover:shadow-md">
                    Auto-Generate Procurement
                </button>
            </form>
        </div>
    </div>

    <!-- Summary Stats -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 animate-fade-in-up stagger-1">
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-yellow-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Pending Requests</p>
            <p class="text-3xl font-bold text-yellow-600 mt-1 font-poppins"><?php echo e($pendingRequests->count()); ?></p>
        </div>
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-purple-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Auto-Generated</p>
            <p class="text-3xl font-bold text-purple-600 mt-1 font-poppins"><?php echo e($autoGeneratedRequests->count()); ?></p>
        </div>
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-red-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Low Stock Items</p>
            <p class="text-3xl font-bold text-red-600 mt-1 font-poppins"><?php echo e($lowStockItems->count()); ?></p>
        </div>
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 p-6 border-l-4 border-green-500">
            <p class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Total Spending (YTD)</p>
            <p class="text-3xl font-bold text-green-600 mt-1 font-poppins">₱<?php echo e(number_format($totalSpending, 0)); ?></p>
        </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <!-- Low Stock Items -->
        <div class="bg-white rounded-2xl ring-1 ring-red-200 shadow-sm p-6 animate-fade-in-up stagger-2">
            <h2 class="text-lg font-semibold text-red-700 mb-4 flex items-center space-x-2">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                <span>Low Stock Alert</span>
            </h2>
            <?php $__empty_1 = true; $__currentLoopData = $lowStockItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <div class="flex items-center justify-between p-3 bg-red-50 rounded-xl mb-2">
                <div>
                    <p class="font-medium text-gray-900"><?php echo e($item->name); ?></p>
                    <p class="text-xs text-gray-500"><?php echo e($item->category); ?></p>
                </div>
                <div class="text-right">
                    <p class="text-sm font-bold text-red-600"><?php echo e($item->available_stock); ?> left</p>
                    <p class="text-xs text-gray-500">Threshold: <?php echo e($item->low_stock_threshold ?? 5); ?></p>
                </div>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <div class="text-center py-6 text-gray-400">
                <svg class="w-10 h-10 mx-auto mb-2 opacity-40" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
                <p>All items are well stocked!</p>
            </div>
            <?php endif; ?>
        </div>

        <!-- Pending Requests -->
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 shadow-sm p-6 animate-fade-in-up stagger-2">
            <h2 class="text-lg font-semibold text-gray-900 mb-4 flex items-center space-x-2">
                <svg class="w-5 h-5 text-yellow-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                <span>Pending Procurement</span>
            </h2>
            <?php $__empty_1 = true; $__currentLoopData = $pendingRequests; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $request): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <div class="flex items-center justify-between p-3 bg-gray-50 rounded-xl mb-2">
                <div>
                    <p class="font-medium text-gray-900"><?php echo e($request->item?->name ?? 'N/A'); ?></p>
                    <p class="text-xs text-gray-500">Qty: <?php echo e($request->quantity); ?> · ₱<?php echo e(number_format($request->total_price, 2)); ?></p>
                </div>
                <div class="flex items-center space-x-2">
                    <?php if($request->auto_generated): ?>
                    <span class="text-xs font-semibold text-purple-600 bg-purple-50 px-2 py-1 rounded-lg">Auto</span>
                    <?php endif; ?>
                    <form method="POST" action="<?php echo e(route('procurement.approve', $request)); ?>" x-data @submit.prevent="$dispatch('open-confirm-modal', { form: $el, title: 'Approve Procurement', message: 'Are you sure you want to approve this procurement request?', type: 'success' })">
                        <?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?>
                        <button type="submit" class="px-3 py-1.5 bg-green-50 text-green-700 rounded-lg text-xs font-semibold hover:bg-green-100 transition-colors">Approve</button>
                    </form>
                </div>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <p class="text-gray-400 text-sm text-center py-4">No pending procurement requests</p>
            <?php endif; ?>
        </div>

        <!-- Auto-Generated Alerts -->
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 shadow-sm p-6 animate-fade-in-up stagger-3">
            <h2 class="text-lg font-semibold text-gray-900 mb-4 flex items-center space-x-2">
                <svg class="w-5 h-5 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                <span>Automated Procurement Alerts</span>
            </h2>
            <?php $__empty_1 = true; $__currentLoopData = $autoGeneratedRequests; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $request): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <div class="flex items-center justify-between p-3 bg-purple-50 rounded-xl mb-2">
                <div>
                    <p class="font-medium text-gray-900"><?php echo e($request->item?->name ?? 'N/A'); ?></p>
                    <p class="text-xs text-gray-500"><?php echo e(Str::limit($request->justification, 60)); ?></p>
                </div>
                <span class="text-xs font-semibold px-2.5 py-1 rounded-lg <?php echo e($request->urgency_level === 'critical' ? 'bg-red-100 text-red-700' : 'bg-orange-100 text-orange-700'); ?>">
                    <?php echo e(ucfirst($request->urgency_level)); ?>

                </span>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <p class="text-gray-400 text-sm text-center py-4">No automated alerts</p>
            <?php endif; ?>
        </div>

        <!-- Recent Deliveries -->
        <div class="bg-white rounded-2xl ring-1 ring-gray-200 shadow-sm p-6 animate-fade-in-up stagger-3">
            <h2 class="text-lg font-semibold text-gray-900 mb-4 flex items-center space-x-2">
                <svg class="w-5 h-5 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
                <span>Recent Deliveries</span>
            </h2>
            <?php $__empty_1 = true; $__currentLoopData = $recentDeliveries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $delivery): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <div class="flex items-center justify-between p-3 bg-gray-50 rounded-xl mb-2">
                <div>
                    <p class="font-medium text-gray-900"><?php echo e($delivery->item?->name ?? 'N/A'); ?></p>
                    <p class="text-xs text-gray-500"><?php echo e($delivery->supplier?->name ?? 'N/A'); ?> · <?php echo e($delivery->received_at ? $delivery->received_at->format('M d, Y') : 'N/A'); ?></p>
                </div>
                <span class="text-sm font-semibold text-gray-700">+<?php echo e($delivery->quantity); ?></span>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <p class="text-gray-400 text-sm text-center py-4">No recent deliveries</p>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Cedric\SEIMS\resources\views/procurement/dashboard.blade.php ENDPATH**/ ?>