<?php

namespace App\Http\Controllers;

use App\Models\ProcurementRequest;
use App\Models\Item;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ProcurementController extends Controller
{
    /**
     * Display a listing of procurement requests
     */
    public function index()
    {
        $procurementRequests = ProcurementRequest::with(['item', 'supplier', 'requester', 'approver'])
            ->orderBy('created_at', 'desc')
            ->paginate(15);

        $pendingCount = ProcurementRequest::pending()->count();
        $autoGeneratedCount = ProcurementRequest::autoGenerated()->pending()->count();

        return view('procurement.index', compact('procurementRequests', 'pendingCount', 'autoGeneratedCount'));
    }

    /**
     * Show the form for creating a new procurement request
     */
    public function create()
    {
        $items = Item::all();
        $suppliers = Supplier::active()->get();

        return view('procurement.create', compact('items', 'suppliers'));
    }

    /**
     * Store a newly created procurement request
     */
    public function store(Request $request)
    {
        $request->validate([
            'item_id' => 'required|exists:items,id',
            'supplier_id' => 'required|exists:suppliers,id',
            'quantity' => 'required|integer|min:1',
            'unit_price' => 'required|numeric|min:0',
            'justification' => 'required|string|max:1000',
            'urgency_level' => 'required|in:low,medium,high,critical',
        ]);

        $totalPrice = $request->quantity * $request->unit_price;

        ProcurementRequest::create([
            'item_id' => $request->item_id,
            'supplier_id' => $request->supplier_id,
            'requested_by' => Auth::id(),
            'quantity' => $request->quantity,
            'unit_price' => $request->unit_price,
            'total_price' => $totalPrice,
            'justification' => $request->justification,
            'urgency_level' => $request->urgency_level,
            'status' => 'pending',
            'auto_generated' => false,
        ]);

        return redirect()->route('procurement.index')
            ->with('success', 'Procurement request submitted successfully!');
    }

    /**
     * Approve a procurement request
     */
    public function approve(ProcurementRequest $procurementRequest)
    {
        return DB::transaction(function () use ($procurementRequest) {
            $procurementRequest = ProcurementRequest::lockForUpdate()->find($procurementRequest->id);

            if ($procurementRequest->status === 'approved') {
                return back()->with('info', 'Procurement request is already approved.');
            }

            if ($procurementRequest->status !== 'pending') {
                return back()->withErrors(['status' => 'Only pending requests can be approved. Current status: ' . $procurementRequest->status]);
            }

            $procurementRequest->update([
                'status' => 'approved',
                'approved_by' => Auth::id(),
                'approved_at' => now(),
            ]);

            return back()->with('success', 'Procurement request approved successfully!');
        });
    }

    /**
     * Reject a procurement request
     */
    public function reject(Request $request, ProcurementRequest $procurementRequest)
    {
        return DB::transaction(function () use ($request, $procurementRequest) {
            $procurementRequest = ProcurementRequest::lockForUpdate()->find($procurementRequest->id);

            if ($procurementRequest->status !== 'pending') {
                return back()->withErrors(['status' => 'Only pending requests can be rejected. Current status: ' . $procurementRequest->status]);
            }

            $procurementRequest->update([
                'status' => 'rejected',
                'notes' => $request->input('reason', 'Rejected by staff'),
            ]);

            return back()->with('success', 'Procurement request rejected.');
        });
    }

    /**
     * Mark procurement request as ordered
     */
    public function markOrdered(ProcurementRequest $procurementRequest)
    {
        return DB::transaction(function () use ($procurementRequest) {
            $procurementRequest = ProcurementRequest::lockForUpdate()->find($procurementRequest->id);

            if ($procurementRequest->status === 'ordered') {
                return back()->with('info', 'Procurement request is already marked as ordered.');
            }

            if ($procurementRequest->status !== 'approved') {
                return back()->withErrors(['status' => 'Only approved requests can be marked as ordered. Current status: ' . $procurementRequest->status]);
            }

            $procurementRequest->update([
                'status' => 'ordered',
                'ordered_at' => now(),
            ]);

            return back()->with('success', 'Procurement request marked as ordered.');
        });
    }

    /**
     * Mark procurement request as received and update stock
     */
    public function markReceived(ProcurementRequest $procurementRequest)
    {
        return DB::transaction(function () use ($procurementRequest) {
            $procurementRequest = ProcurementRequest::lockForUpdate()->find($procurementRequest->id);

            if ($procurementRequest->status === 'received') {
                return back()->with('info', 'Procurement request has already been received.');
            }

            if ($procurementRequest->status !== 'ordered') {
                return back()->withErrors(['status' => 'Only ordered requests can be marked as received. Current status: ' . $procurementRequest->status]);
            }

            $procurementRequest->update([
                'status' => 'received',
                'received_at' => now(),
            ]);

            // Update item stock only once, inside the transaction after confirming status
            $item = $procurementRequest->item;
            $item->increment('total_stock', $procurementRequest->quantity);
            $item->increment('available_stock', $procurementRequest->quantity);

            return back()->with('success', 'Procurement request marked as received. Stock updated.');
        });
    }

    /**
     * Generate automated low stock alerts
     */
    public function generateLowStockAlerts()
    {
        $lowStockItems = Item::lowStock()->get();
        $alertsGenerated = 0;

        foreach ($lowStockItems as $item) {
            // Check if there's already a pending procurement request
            $existingRequest = ProcurementRequest::where('item_id', $item->id)
                ->whereIn('status', ['pending', 'approved', 'ordered'])
                ->exists();

            if (!$existingRequest) {
                ProcurementRequest::autoGenerateForLowStock($item);
                $alertsGenerated++;
            }
        }

        return back()->with('success', "Generated {$alertsGenerated} automated procurement requests for low stock items.");
    }

    /**
     * Show procurement dashboard with analytics
     */
    public function dashboard()
    {
        $pendingRequests = ProcurementRequest::pending()->with('item')->get();
        $autoGeneratedRequests = ProcurementRequest::autoGenerated()->pending()->with('item')->get();
        
        $totalSpending = ProcurementRequest::where('status', 'received')
            ->whereYear('received_at', now()->year)
            ->sum('total_price');

        $lowStockItems = Item::lowStock()->get();
        
        $recentDeliveries = ProcurementRequest::where('status', 'received')
            ->orderBy('received_at', 'desc')
            ->take(10)
            ->with(['item', 'supplier'])
            ->get();

        return view('procurement.dashboard', compact(
            'pendingRequests',
            'autoGeneratedRequests',
            'totalSpending',
            'lowStockItems',
            'recentDeliveries'
        ));
    }
}
