<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProcurementRequest extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'item_id',
        'supplier_id',
        'requested_by',
        'quantity',
        'unit_price',
        'total_price',
        'justification',
        'urgency_level',
        'status',
        'approved_by',
        'approved_at',
        'ordered_at',
        'received_at',
        'notes',
        'auto_generated',
        'stock_threshold_triggered',
    ];

    /**
     * The attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'quantity' => 'integer',
            'unit_price' => 'decimal:2',
            'total_price' => 'decimal:2',
            'approved_at' => 'datetime',
            'ordered_at' => 'datetime',
            'received_at' => 'datetime',
            'auto_generated' => 'boolean',
            'stock_threshold_triggered' => 'boolean',
        ];
    }

    /**
     * Relationships
     */
    public function item()
    {
        return $this->belongsTo(Item::class)->withDefault([
            'name' => 'Deleted Item',
            'image_path' => null,
        ]);
    }

    public function supplier()
    {
        return $this->belongsTo(Supplier::class)->withDefault([
            'name' => 'Unknown Supplier',
        ]);
    }

    public function requester()
    {
        return $this->belongsTo(User::class, 'requested_by');
    }

    public function approver()
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    /**
     * Auto-generate procurement request when stock is low
     */
    public static function autoGenerateForLowStock(Item $item)
    {
        if ($item->available_stock <= $item->low_stock_threshold) {
            $supplier = $item->preferredSupplier ?? Supplier::where('status', 'active')->first();

            if (!$supplier) {
                return null;
            }

            $quantityNeeded = max($item->reorder_quantity ?? 10, $item->low_stock_threshold * 2);

            // Use the first admin user as the system requester, or fall back to any staff
            $systemUser = \App\Models\User::where('role', 'admin')->first()
                ?? \App\Models\User::where('role', 'staff')->first();

            if (!$systemUser) {
                return null;
            }

            return self::create([
                'item_id' => $item->id,
                'supplier_id' => $supplier->id,
                'requested_by' => $systemUser->id,
                'quantity' => $quantityNeeded,
                'unit_price' => $item->unit_price ?? 0,
                'total_price' => ($item->unit_price ?? 0) * $quantityNeeded,
                'justification' => "Automated low stock alert: Available stock ({$item->available_stock}) is below threshold ({$item->low_stock_threshold})",
                'urgency_level' => 'high',
                'status' => 'pending',
                'auto_generated' => true,
                'stock_threshold_triggered' => true,
            ]);
        }

        return null;
    }

    /**
     * Scope for pending requests
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope for auto-generated requests
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }
}
